#
# Path to this kit's root directory.
# Absolute or relative to this config file.
# If not specified, defaults to the folder that holds this config file.
#
:path: ../test_kit
#
# Holds kit configuration.
#
:kit:
  #
  # Database configuration for kit.
  #
  :db:
    #
    # Database adapter to use. Available options:
    #   :sqlite3
    #
    :adapter: :sqlite3
    #
    # Path to the files to save the sqlite3 database.
    # Absolute or relative to this config file.
    #
    :path: ../db/info.sqlite
#
# Holds bits configuration.
#
:bits:
#
# Holds actions configuration.
#
:actions: